### ISSUE TITLE
It seems that part of scan is missing from the segmentation file

### ISSUE THREAD

**Issue by saladcat** [qq456cvb/CanonicalVoting#3]
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/22851795/162659555-61859624-772f-4b4f-8d6a-c9ee4e5488d5.png">

**Comment by qq456cvb** [comment]
Hi, this error is due to that we removed some ambiguous Scan2CAD annotations for Bathtub (wordnet id: 02808440) category. You can download our fixed annotations on [Google Drive](https://drive.google.com/file/d/1-D4gvCcSIXKZGGmi1lHv91fqKq46sYJn/view?usp=sharing). The corresponding segment file is already fixed, so there is inconsistency. We also update the README to explain this. Feel free if you have any further questions.

**Comment by saladcat** [comment]
Thanks for your reply, would you like to share the code to generate Scan2CAD model segments and ground-truth boxes?

**Comment by qq456cvb** [comment]
We annotate Scan2CAD model segments manually for each scene. The code for generating ground-truth boxes can be found [here](https://drive.google.com/file/d/1-DszHkLystRQu0104yK5bkc2ESUrQg8Q/view?usp=sharing).

**Comment by saladcat** [comment]
Thank you so much！
